######### Author: Grace Hansen #########
#This script specifies variables for the Snakemake file.
#This script is part of the snakemake TWAS pipeline.

#Snakemake configuration file

#Specify paths to data files

#Paths must end with forward slash

#project directory
dir: /project2/nobrega/grace/TAD_fusion

#Scripts directory:
scripts: /project2/nobrega/grace/TAD_fusion/scripts/

# Genome assembly
fasta: /project2/nobrega/grace/genos/hg19/fasta/GRCh37.p13.genome.fa

#Specify samples
samples: samples.txt

chrs: ["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","X","Y"]

#Parameters
RE: MboI #Restriction enzyme
threshold: 0.25 #Score threshold for TADs
frags_per_TAD: 15
res: 1000 #Resolution for HiC
window: 15000 #Window size to use when finding TADs
probe_length: 120 #Length of internal sequence of probes
STAR_params: /project2/nobrega/grace/TAD_fusion/STAR_params